Can't load '/usr/local/software/slurm/slurm-20.11.9-rhel8/lib64/perl5/auto/Slurm/Slurm.so' for module Slurm: libperl.so.5.26: cannot open shared object file: No such file or directory at /usr/lib64/perl5/DynaLoader.pm line 190, <DATA> line 602.
 at /usr/local/software/slurm/current-rhel8/bin/generate_pbs_nodefile line 18.
Compilation failed in require at /usr/local/software/slurm/current-rhel8/bin/generate_pbs_nodefile line 18, <DATA> line 602.
BEGIN failed--compilation aborted at /usr/local/software/slurm/current-rhel8/bin/generate_pbs_nodefile line 18, <DATA> line 602.
WARNING: Logging before flag parsing goes to stderr.
W0517 20:30:44.390770 47886980764544 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
Warning: CARLA failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'carla'
2022-05-17 20:30:47,339	INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2022-05-17_20-30-47_339511_28871/logs.
2022-05-17 20:30:47,451	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:53345 to respond...
2022-05-17 20:30:47,612	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:15424 to respond...
2022-05-17 20:30:47,614	INFO services.py:806 -- Starting Redis shard with 10.0 GB max memory.
2022-05-17 20:30:47,634	INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2022-05-17_20-30-47_339511_28871/logs.
2022-05-17 20:30:47,635	WARNING services.py:1294 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
2022-05-17 20:30:47,635	INFO services.py:1442 -- Starting the Plasma object store with 20.0 GB memory using /dev/shm.
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0517 20:30:47.706174 28871 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2022-05-17_20-30-47_339511_28871/sockets/plasma_store, retrying 300 more times
2022-05-17 20:30:48,370	INFO tune.py:61 -- Tip: to resume incomplete experiments, pass resume='prompt' or resume=True to run()
2022-05-17 20:30:48,371	INFO tune.py:232 -- Starting a new experiment.
W0517 20:30:48.404870 47886980764544 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:131: The name tf.VERSION is deprecated. Please use tf.version.VERSION instead.

W0517 20:30:48.405247 47886980764544 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:136: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

2022-05-17 20:30:48,494	WARNING util.py:64 -- The `start_trial` operation took 0.11339521408081055 seconds to complete, which may be a performance bottleneck.
W0517 20:38:27.977854 47886980764544 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:114: The name tf.Summary is deprecated. Please use tf.compat.v1.Summary instead.

2022-05-17 20:45:10,033	WARNING util.py:64 -- The `save_to_disk` operation took 0.7937569618225098 seconds to complete, which may be a performance bottleneck.
2022-05-17 20:45:10,037	WARNING util.py:64 -- The `process_trial` operation took 0.8063018321990967 seconds to complete, which may be a performance bottleneck.
2022-05-17 20:50:20,502	WARNING util.py:64 -- The `experiment_checkpoint` operation took 0.11489224433898926 seconds to complete, which may be a performance bottleneck.
2022-05-17 20:52:33,657	WARNING util.py:64 -- The `save_to_disk` operation took 0.4540884494781494 seconds to complete, which may be a performance bottleneck.
2022-05-17 20:52:33,661	WARNING util.py:64 -- The `process_trial` operation took 0.4663369655609131 seconds to complete, which may be a performance bottleneck.
2022-05-17 20:59:56,876	WARNING util.py:64 -- The `save_to_disk` operation took 0.4424917697906494 seconds to complete, which may be a performance bottleneck.
2022-05-17 20:59:56,879	WARNING util.py:64 -- The `process_trial` operation took 0.45296430587768555 seconds to complete, which may be a performance bottleneck.
2022-05-17 21:07:19,539	WARNING util.py:64 -- The `save_to_disk` operation took 0.4388737678527832 seconds to complete, which may be a performance bottleneck.
2022-05-17 21:07:19,542	WARNING util.py:64 -- The `process_trial` operation took 0.4505152702331543 seconds to complete, which may be a performance bottleneck.
2022-05-17 21:11:00,476	WARNING util.py:64 -- The `experiment_checkpoint` operation took 0.11579346656799316 seconds to complete, which may be a performance bottleneck.
2022-05-17 21:14:42,257	WARNING util.py:64 -- The `save_to_disk` operation took 0.470322847366333 seconds to complete, which may be a performance bottleneck.
2022-05-17 21:14:42,260	WARNING util.py:64 -- The `process_trial` operation took 0.4815826416015625 seconds to complete, which may be a performance bottleneck.
2022-05-17 21:22:04,811	WARNING util.py:64 -- The `save_to_disk` operation took 0.4845242500305176 seconds to complete, which may be a performance bottleneck.
2022-05-17 21:22:04,813	WARNING util.py:64 -- The `process_trial` operation took 0.49509620666503906 seconds to complete, which may be a performance bottleneck.
2022-05-17 21:29:27,592	WARNING util.py:64 -- The `save_to_disk` operation took 0.47707247734069824 seconds to complete, which may be a performance bottleneck.
2022-05-17 21:29:27,594	WARNING util.py:64 -- The `process_trial` operation took 0.4883248805999756 seconds to complete, which may be a performance bottleneck.
slurmstepd: error: *** JOB 61286045 ON gpu-e-8 CANCELLED AT 2022-05-17T21:30:52 DUE TO TIME LIMIT ***
