Loading rhel8/default-icl
  Loading requirement: dot rhel8/slurm singularity/current rhel8/global
    cuda/11.4 intel/compilers/2020.2 intel/mkl/2020.2 intel/impi/2020.2/intel
    intel/libs/idb/2020.2 intel/libs/tbb/2020.2 intel/libs/ipp/2020.2
    intel/libs/daal/2020.2 intel/bundles/complib/2020.2
WARNING: Logging before flag parsing goes to stderr.
W0518 15:31:39.638670 22443803681664 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
Warning: CARLA failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'carla'
2022-05-18 15:31:48,843	INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2022-05-18_15-31-48_842215_442529/logs.
2022-05-18 15:31:48,993	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:15492 to respond...
2022-05-18 15:31:49,995	INFO services.py:414 -- Failed to connect to the redis server, retrying.
2022-05-18 15:31:49,995	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:15492 to respond...
2022-05-18 15:31:50,107	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:44453 to respond...
2022-05-18 15:31:50,108	INFO services.py:806 -- Starting Redis shard with 10.0 GB max memory.
2022-05-18 15:31:50,164	INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2022-05-18_15-31-48_842215_442529/logs.
2022-05-18 15:31:50,165	WARNING services.py:1294 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
2022-05-18 15:31:50,165	INFO services.py:1442 -- Starting the Plasma object store with 20.0 GB memory using /dev/shm.
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0518 15:31:50.257769 442529 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2022-05-18_15-31-48_842215_442529/sockets/plasma_store, retrying 300 more times
2022-05-18 15:31:51,277	INFO tune.py:61 -- Tip: to resume incomplete experiments, pass resume='prompt' or resume=True to run()
2022-05-18 15:31:51,277	INFO tune.py:232 -- Starting a new experiment.
W0518 15:31:51.295169 22443803681664 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:131: The name tf.VERSION is deprecated. Please use tf.version.VERSION instead.

W0518 15:31:51.295376 22443803681664 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:136: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

W0518 15:40:56.790744 22443803681664 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:114: The name tf.Summary is deprecated. Please use tf.compat.v1.Summary instead.

2022-05-18 15:47:12,182	WARNING util.py:64 -- The `save_to_disk` operation took 0.8993902206420898 seconds to complete, which may be a performance bottleneck.
2022-05-18 15:47:12,186	WARNING util.py:64 -- The `process_trial` operation took 0.9080822467803955 seconds to complete, which may be a performance bottleneck.
2022-05-18 15:48:35,248	WARNING util.py:64 -- The `process_trial` operation took 0.10844993591308594 seconds to complete, which may be a performance bottleneck.
2022-05-18 15:54:07,789	WARNING util.py:64 -- The `save_to_disk` operation took 0.42432188987731934 seconds to complete, which may be a performance bottleneck.
2022-05-18 15:54:07,791	WARNING util.py:64 -- The `process_trial` operation took 0.43231773376464844 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:01:03,315	WARNING util.py:64 -- The `save_to_disk` operation took 0.42391395568847656 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:01:03,316	WARNING util.py:64 -- The `process_trial` operation took 0.430941104888916 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:07:59,821	WARNING util.py:64 -- The `save_to_disk` operation took 0.43157196044921875 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:07:59,826	WARNING util.py:64 -- The `process_trial` operation took 0.4414834976196289 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:14:56,574	WARNING util.py:64 -- The `save_to_disk` operation took 0.4248487949371338 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:14:56,576	WARNING util.py:64 -- The `process_trial` operation took 0.43190503120422363 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:21:53,119	WARNING util.py:64 -- The `save_to_disk` operation took 0.43613314628601074 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:21:53,120	WARNING util.py:64 -- The `process_trial` operation took 0.4429011344909668 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:28:49,516	WARNING util.py:64 -- The `save_to_disk` operation took 0.43589305877685547 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:28:49,519	WARNING util.py:64 -- The `process_trial` operation took 0.44417619705200195 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:35:46,249	WARNING util.py:64 -- The `save_to_disk` operation took 0.4403519630432129 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:35:46,250	WARNING util.py:64 -- The `process_trial` operation took 0.4471924304962158 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:38:34,952	WARNING util.py:64 -- The `process_trial` operation took 0.3785679340362549 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:42:39,878	WARNING util.py:64 -- The `save_to_disk` operation took 1.5403006076812744 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:42:39,882	WARNING util.py:64 -- The `process_trial` operation took 1.5496070384979248 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:49:25,571	WARNING util.py:64 -- The `save_to_disk` operation took 0.4122753143310547 seconds to complete, which may be a performance bottleneck.
2022-05-18 16:49:25,572	WARNING util.py:64 -- The `process_trial` operation took 0.4190552234649658 seconds to complete, which may be a performance bottleneck.
slurmstepd: error: *** JOB 61334681 ON cpu-q-234 CANCELLED AT 2022-05-18T16:52:16 ***
