Can't load '/usr/local/software/slurm/slurm-20.11.9-rhel8/lib64/perl5/auto/Slurm/Slurm.so' for module Slurm: libperl.so.5.26: cannot open shared object file: No such file or directory at /usr/lib64/perl5/DynaLoader.pm line 190, <DATA> line 602.
 at /usr/local/software/slurm/current-rhel8/bin/generate_pbs_nodefile line 18.
Compilation failed in require at /usr/local/software/slurm/current-rhel8/bin/generate_pbs_nodefile line 18, <DATA> line 602.
BEGIN failed--compilation aborted at /usr/local/software/slurm/current-rhel8/bin/generate_pbs_nodefile line 18, <DATA> line 602.
WARNING: Logging before flag parsing goes to stderr.
W0519 10:46:22.420933 48001223721856 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
Warning: CARLA failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'carla'
2022-05-19 10:46:29,798	INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2022-05-19_10-46-29_797994_18804/logs.
2022-05-19 10:46:29,944	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:52820 to respond...
2022-05-19 10:46:30,946	INFO services.py:414 -- Failed to connect to the redis server, retrying.
2022-05-19 10:46:30,946	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:52820 to respond...
2022-05-19 10:46:31,060	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:36389 to respond...
2022-05-19 10:46:31,061	INFO services.py:806 -- Starting Redis shard with 10.0 GB max memory.
2022-05-19 10:46:31,104	INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2022-05-19_10-46-29_797994_18804/logs.
2022-05-19 10:46:31,105	WARNING services.py:1294 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
2022-05-19 10:46:31,105	INFO services.py:1442 -- Starting the Plasma object store with 20.0 GB memory using /dev/shm.
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0519 10:46:31.199273 18804 io.cc:168] Connection to IPC socket failed for pathname /tmp/ray/session_2022-05-19_10-46-29_797994_18804/sockets/plasma_store, retrying 300 more times
2022-05-19 10:46:32,306	INFO tune.py:65 -- Did not find checkpoint file in ./ray_mopo/HalfCheetah/halfcheetah_diverse_polocies_101e3.
2022-05-19 10:46:32,306	INFO tune.py:232 -- Starting a new experiment.
W0519 10:46:32.350620 48001223721856 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:131: The name tf.VERSION is deprecated. Please use tf.version.VERSION instead.

W0519 10:46:32.350973 48001223721856 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:136: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

2022-05-19 10:46:32,453	WARNING util.py:64 -- The `start_trial` operation took 0.13920354843139648 seconds to complete, which may be a performance bottleneck.
W0519 11:08:46.506771 48001223721856 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:114: The name tf.Summary is deprecated. Please use tf.compat.v1.Summary instead.

2022-05-19 11:15:30,295	WARNING util.py:64 -- The `save_to_disk` operation took 0.9503614902496338 seconds to complete, which may be a performance bottleneck.
2022-05-19 11:15:30,297	WARNING util.py:64 -- The `process_trial` operation took 0.9616994857788086 seconds to complete, which may be a performance bottleneck.
2022-05-19 11:22:59,198	WARNING util.py:64 -- The `save_to_disk` operation took 0.5407321453094482 seconds to complete, which may be a performance bottleneck.
2022-05-19 11:22:59,201	WARNING util.py:64 -- The `process_trial` operation took 0.5513100624084473 seconds to complete, which may be a performance bottleneck.
2022-05-19 11:30:27,449	WARNING util.py:64 -- The `save_to_disk` operation took 0.44829773902893066 seconds to complete, which may be a performance bottleneck.
2022-05-19 11:30:27,451	WARNING util.py:64 -- The `process_trial` operation took 0.46012091636657715 seconds to complete, which may be a performance bottleneck.
2022-05-19 11:37:58,108	WARNING util.py:64 -- The `save_to_disk` operation took 0.4666023254394531 seconds to complete, which may be a performance bottleneck.
2022-05-19 11:37:58,110	WARNING util.py:64 -- The `process_trial` operation took 0.47854065895080566 seconds to complete, which may be a performance bottleneck.
slurmstepd: error: *** JOB 61392335 ON gpu-e-18 CANCELLED AT 2022-05-19T11:44:59 DUE TO TIME LIMIT ***
