Can't load '/usr/local/software/slurm/slurm-20.11.9-rhel8/lib64/perl5/auto/Slurm/Slurm.so' for module Slurm: libperl.so.5.26: cannot open shared object file: No such file or directory at /usr/lib64/perl5/DynaLoader.pm line 190, <DATA> line 602.
 at /usr/local/software/slurm/current-rhel8/bin/generate_pbs_nodefile line 18.
Compilation failed in require at /usr/local/software/slurm/current-rhel8/bin/generate_pbs_nodefile line 18, <DATA> line 602.
BEGIN failed--compilation aborted at /usr/local/software/slurm/current-rhel8/bin/generate_pbs_nodefile line 18, <DATA> line 602.
WARNING: Logging before flag parsing goes to stderr.
W0519 14:57:01.703548 47345212900224 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
Warning: CARLA failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'carla'
2022-05-19 14:57:09,069	INFO node.py:498 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2022-05-19_14-57-09_068675_31133/logs.
2022-05-19 14:57:09,216	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:13932 to respond...
2022-05-19 14:57:10,218	INFO services.py:414 -- Failed to connect to the redis server, retrying.
2022-05-19 14:57:10,218	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:13932 to respond...
2022-05-19 14:57:10,331	INFO services.py:409 -- Waiting for redis server at 127.0.0.1:30301 to respond...
2022-05-19 14:57:10,332	INFO services.py:806 -- Starting Redis shard with 10.0 GB max memory.
2022-05-19 14:57:10,387	INFO node.py:512 -- Process STDOUT and STDERR is being redirected to /tmp/ray/session_2022-05-19_14-57-09_068675_31133/logs.
2022-05-19 14:57:10,388	WARNING services.py:1294 -- Warning: Capping object memory store to 20.0GB. To increase this further, specify `object_store_memory` when calling ray.init() or ray start.
2022-05-19 14:57:10,388	INFO services.py:1442 -- Starting the Plasma object store with 20.0 GB memory using /dev/shm.
2022-05-19 14:57:11,178	INFO tune.py:65 -- Did not find checkpoint file in ./ray_mopo/HalfCheetah/halfcheetah_d3rlpy_pep2_101e3.
2022-05-19 14:57:11,178	INFO tune.py:232 -- Starting a new experiment.
W0519 14:57:11.241232 47345212900224 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:131: The name tf.VERSION is deprecated. Please use tf.version.VERSION instead.

W0519 14:57:11.241608 47345212900224 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:136: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

2022-05-19 14:57:11,321	WARNING util.py:64 -- The `start_trial` operation took 0.1318521499633789 seconds to complete, which may be a performance bottleneck.
W0519 15:04:56.714166 47345212900224 deprecation_wrapper.py:119] From /rds/user/ajc348/hpc-work/mopo/.env/lib/python3.6/site-packages/ray/tune/logger.py:114: The name tf.Summary is deprecated. Please use tf.compat.v1.Summary instead.

2022-05-19 15:11:38,335	WARNING util.py:64 -- The `save_to_disk` operation took 0.9737565517425537 seconds to complete, which may be a performance bottleneck.
2022-05-19 15:11:38,338	WARNING util.py:64 -- The `process_trial` operation took 0.9850068092346191 seconds to complete, which may be a performance bottleneck.
2022-05-19 15:18:16,064	WARNING util.py:64 -- The `experiment_checkpoint` operation took 0.17711472511291504 seconds to complete, which may be a performance bottleneck.
2022-05-19 15:19:00,309	WARNING util.py:64 -- The `save_to_disk` operation took 0.4707176685333252 seconds to complete, which may be a performance bottleneck.
2022-05-19 15:19:00,312	WARNING util.py:64 -- The `process_trial` operation took 0.481581449508667 seconds to complete, which may be a performance bottleneck.
2022-05-19 15:26:20,854	WARNING util.py:64 -- The `save_to_disk` operation took 0.43541646003723145 seconds to complete, which may be a performance bottleneck.
2022-05-19 15:26:20,857	WARNING util.py:64 -- The `process_trial` operation took 0.44657015800476074 seconds to complete, which may be a performance bottleneck.
2022-05-19 15:33:49,177	WARNING util.py:64 -- The `save_to_disk` operation took 0.5042197704315186 seconds to complete, which may be a performance bottleneck.
2022-05-19 15:33:49,180	WARNING util.py:64 -- The `process_trial` operation took 0.5158336162567139 seconds to complete, which may be a performance bottleneck.
2022-05-19 15:41:28,316	WARNING util.py:64 -- The `save_to_disk` operation took 0.5164532661437988 seconds to complete, which may be a performance bottleneck.
2022-05-19 15:41:28,319	WARNING util.py:64 -- The `process_trial` operation took 0.5277183055877686 seconds to complete, which may be a performance bottleneck.
2022-05-19 15:49:07,691	WARNING util.py:64 -- The `save_to_disk` operation took 0.5219113826751709 seconds to complete, which may be a performance bottleneck.
2022-05-19 15:49:07,693	WARNING util.py:64 -- The `process_trial` operation took 0.533336877822876 seconds to complete, which may be a performance bottleneck.
slurmstepd: error: *** JOB 61403841 ON gpu-e-17 CANCELLED AT 2022-05-19T15:56:07 DUE TO TIME LIMIT ***
